version: '3.8'

services:
  traefik:
    image: 'traefik:v2.2'
    command: 
    - '--api.insecure=true'
    - '--providers.docker'
    ports:
    # The HTTP port
    - "80:80"
    # The Web UI (enabled by --api.insecure=true)
    - "8080:8080"
    volumes:
    # So that Traefik can listen to the Docker events
    - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: 'containous/whoami:v1.5.0'
    labels:
    - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
